---
github:
  owner: expcapitaldev
  repo: sentry-cordova
changelogPolicy: auto
statusProvider:
  name: github
artifactProvider:
  name: github
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: npm
  - name: github
    tagPrefix: v
