---
github:
  owner: getsentry
  repo: sentry-cordova
changelogPolicy: auto
statusProvider:
  name: github
artifactProvider:
  name: github
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: npm
  - name: github
    tagPrefix: v
  - name: registry
    sdks:
      npm:sentry-cordova:
        includeNames: /none/
