export {
  addBreadcrumb,
  create,
  captureEvent,
  captureException,
  captureMessage,
  popScope,
  pushScope,
  setDist,
  setUserContext,
  setExtraContext,
  setRelease,
  setTagsContext,
  setVersion,
} from './frontend';
